### ISSUE TITLE
Make height / min-height configurable

### ISSUE THREAD

**Issue by supremebeing7** [blocknotes/activeadmin_trumbowyg#1]
Is there any reason the editor box needs a min-height of 300px? I know I can edit the CSS but it would be nice to have that configurable within activeadmin... something like
```
f.input :some_field, as: :trumbowyg, height: 160
```

**Comment by blocknotes** [comment]
Hi @supremebeing7 
min-height of 300px is set in Trumbowyg styles:
[https://github.com/Alex-D/Trumbowyg/blob/develop/src/ui/sass/trumbowyg.scss#L42](https://github.com/Alex-D/Trumbowyg/blob/develop/src/ui/sass/trumbowyg.scss#L42)
The *height* option... I'll think about it. I don't like the idea to create an option only to change something style-related.

**Comment by blocknotes** [comment]
It can be changed via CSS, I prefer to keep config clean from styles
