### ISSUE TITLE
Not uploaded images

### ISSUE THREAD

**Issue by zhandosalmaty** [blocknotes/activeadmin_trumbowyg#11]
can you paste this repo example app?

**Comment by blocknotes** [comment]
I'm sorry if I reply so late @zhandosalmaty - I improved the README and added the relevant files to use the Trumbowyg upload plugin with Active Storage. See [here](https://github.com/blocknotes/activeadmin_trumbowyg/tree/master/examples/upload_plugin_using_activestorage)

**Comment by zhandosalmaty** [comment]
Hello! Thank you! I use your gem in few projects, Trumbowyg in Active Admin work very well. I think Rails is better!
