### ISSUE TITLE
Import file n

### ISSUE THREAD

**Issue by KathChalmers** [blocknotes/activeadmin_trumbowyg#14]
Thanks so much for your cool gem. Although the instructions were very clear, I'm getting the following error:

    SassC::SyntaxError at /admin/messages    
    Error: File to import not found or unreadable: activeadmin/trumbowyg/trumbowyg    
            on line 17 of app/assets/stylesheets/active_admin.scss    
    >> @import 'activeadmin/trumbowyg/trumbowyg';

**Comment by blocknotes** [comment]
Ehi @KathChalmers, could you try a bundle update of your sass library (sassc I suppose). I saw similar errors with some old versions

**Comment by blocknotes** [comment]
Close due to missing feedback.
Please reopen if needed.
