### ISSUE TITLE
"startContainer" issue loading a text containing a <b> tag

### ISSUE THREAD

**Issue by roberquesada** [blocknotes/activeadmin_trumbowyg#17]
Hi!!

I have been getting a random error when I have been trying to load the editor in my project. The error is that the editing tools are not displayed and any changes made to the text are not saved.

The following error message is displayed in the browser:

`jQuery.Deferred exception: Cannot read property 'startContainer' of null TypeError: Cannot read property 'startContainer' of null`

After doing some tests, I have detected that this error occurs when the text contains a tag of type `<b>`.

I downgraded from version `0.2.12` to version `0.2.10` and now works properly.

I don't know if this is an isolated error in my project but I wanted to report it in case someone else could reproduce it 😄

**Comment by blocknotes** [comment]
> After doing some tests, I have detected that this error occurs when the text contains a tag of type .

Hey @roberquesada.
Can share a sample of the content that it's breaking the editor?
It would help a lot.

**Comment by roberquesada** [comment]
> > After doing some tests, I have detected that this error occurs when the text contains a tag of type .
> 
> Hey @roberquesada.
> Can share a sample of the content that it's breaking the editor?
> It would help a lot.

@blocknotes Yes. sure!

This is and sample of content that is breaking the editor.
`<p><b>Test</b></p>`

**Comment by blocknotes** [comment]
Sorry to come back so late @roberquesada 
I made some checks and I confirm the issue, it seems related to Trumbowyg unfortunately - prepared a test here:
https://jsfiddle.net/dLvfeaob/1

Opened a ticket here: https://github.com/Alex-D/Trumbowyg/issues/1233

**Comment by blocknotes** [comment]
Regarding this issue: Trumbowyg has been fixed by the author.

So: fixed in the gem version [0.2.16](https://github.com/blocknotes/activeadmin_trumbowyg/releases/tag/v0.2.16)
