### ISSUE TITLE
Invalid CSS after "0": expected expression (e.g. 1px, bold), was ";"

### ISSUE THREAD

**Issue by hlidotbe** [blocknotes/activeadmin_trumbowyg#7]
Hi,

It seems commit c146f3c97cf16cdde2e26618ccf8017a1731e8e0 introduced an issue.

In app/assets/stylesheets/activeadmin/_trumbowyg_input.sass, L12 and L13 have a semi-colon that shouldn't be there.

If I manage to have the time I'll do a PR.

**Comment by blocknotes** [comment]
Thank you @hlidotbe - fixed
