### ISSUE TITLE
Alpha installation for active admin 2

### ISSUE THREAD

**Issue by markblasdls** [blocknotes/activeadmin_trumbowyg#8]
git clone error while bundle install

Git error: command `git clone 'https://github.com/blocknotes/activeadmin_trumbowyg'
"/home/vagrant/.rvm/gems/ruby-2.4.2/cache/bundler/git/activeadmin_trumbowyg-496c7d51213ca40cb4a2c80545bc34189a509d05" --bare --no-hardlinks --quiet` in directory

also tried .git but still error.

Git error: command `git clone 'git@github.com:blocknotes/activeadmin_trumbowyg.git'
"/home/vagrant/.rvm/gems/ruby-2.4.2/cache/bundler/git/activeadmin_trumbowyg-6eedea88abc41d5ccf8540a9520ea45d42ffd468" --bare --no-hardlinks --quiet` in directory
/vagrant_data/activeadmintest has failed.

**Comment by blocknotes** [comment]
Sorry to reply so late, but it doens't seem related to this `activeadmin_trumbowyg` component.
